### ISSUE TITLE
file upload with file drop support

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-mdl-bridge#3]
For your collection.. Did that at work. :wink: 

[mdl-file.zip](https://github.com/aurelia-ui-toolkits/aurelia-mdl-bridge/files/381603/mdl-file.zip)

**Comment by Thanood** [comment]
Sorry, wrong css. Here it is:

``` css
mdl-file {
  border: solid 1px transparent;
  display: block;
  margin: 10px 0;
}

mdl-file.mdl-file--hover {
  border: dashed 1px grey;
}

mdl-file .mdl-button--file input {
  cursor: pointer;
  height: 100%;
  opacity: 0;
  position: absolute;
  right: 0;
  top: 0;
  width: 300px;
  z-index: 4;
}

mdl-file .mdl-textfield--file .mdl-textfield__input {
  box-sizing: border-box;
  width: calc(100% - 32px);
}

mdl-file .mdl-textfield--file .mdl-button--file {
  right: 0;
}
```
